### ISSUE TITLE
Recording duplicated and no markers inserted

### ISSUE THREAD

**Issue by fefo-dev** [Davidj361/OBS-ChapterMarker#3] opened 2021-08-10 02:13 UTC
First of all thanks for the tool, it's very useful although just in theory so far.

I updated it just before streaming/recording today and tested with a quick recording. 3 markers, all done correctly. However during stream it didn't work and two recordings were generated: 'video.mkv' and 'video - ChapterMarker.mkv'. No markers on the main file; the second file is seemingly blank/unplayable and about the size a recording after the marker point should be. OBS also failed to close gracefully after the fact.

Let me know if you need more info. As I leave it recording unattended I don't have a lot of variables outside of video lenght (few seconds vs hours) and just recording and recording/streaming.

Thanks a lot.

**Comment by Davidj361** [comment] 2021-08-12 14:49
@fefo-dev 
> I updated it just before streaming/recording today and tested with a quick recording. 3 markers, all done correctly. However during stream it didn't work and two recordings were generated: 'video.mkv' and 'video - ChapterMarker.mkv'.
The plugin creates a duplicate video of the recording where the encoding is copied as well to avoid re-encoding which is `video - ChapterMarker.mkv`. It deletes the original video and renames it to the original video if there are no problems detected during the process.

>No markers on the main file; the second file is seemingly blank/unplayable and about the size a recording after the marker point should be. OBS also failed to close gracefully after the fact.
Sounds like there was an error in copying the video file via ffmpeg libraries.

> Let me know if you need more info. As I leave it recording unattended I don't have a lot of variables outside of video lenght (few seconds vs hours) and just recording and recording/streaming.

Can you tell me whether you are utilizing 64-bit or 32-bit OBS? What operating system are you on? What version of OBS are you running?

**Comment by fefo-dev** [comment] 2021-08-12 18:52
OBS Studio 27.0.1 64-bits on Windows 10 20H2.

Thanks for explaining how it works. Quite simple, although you should note this for users without a lot of space - those files can be huge.

While the marker video was empty, you could see a split on the seek bar while playing it (I'm using MPE-BE) right about where the marker should have been. Not a chapter per se, but it had a lighter shade than normal before the point perhaps to denote a empty area.

For the record main file had about ~55GB and the marker had 40GB. I'll try to check on smaller recordings but maybe ffmpeg gets clogged by the size?

**Comment by Davidj361** [comment] 2021-08-13 23:12
> For the record main file had about ~55GB and the marker had 40GB.

Do you have enough space on your drive to hold the original recording and a duplicate of it? I have to do a workaround by duplicating the video because as far as I know I can't directly interact with OBS recording and encoding video files. OBS itself would need the feature in its base code to avoid the duplicate video work around.

> I'll try to check on smaller recordings but maybe ffmpeg gets clogged by the size?

Could be possible, I haven't tested with large sized recordings.

**Comment by fefo-dev** [comment] 2021-08-14 14:39
> Do you have enough space on your drive to hold the original recording and a duplicate of it?

Not anymore as I need the storage space. No harm since markers are just for editing.

**Comment by Davidj361** [comment] 2021-08-14 18:12
Let me know if it still breaks when you have enough space on your drive for the duplicate video. I think that was the problem. I'll be sure to leave a disclaimer in the description.

**Comment by Davidj361** [comment] 2021-08-28 08:21
I see the problem you're having. The chapter marker version was a smaller file size and both files existed. Just finished recording a 2 hour video (~10GB) and it took 5-10 minutes to finalize the chapter marker version of the video where it deleted the original video and renamed itself once it was done processing. 

I'm surprised it takes so long to copy over the encoding data, not sure if this is a problem caused by having this processed in a thread where it's being put to sleep too much. Or the example code that I used for copying video encoding under lib ffmpeg is just botched and has bad time complexity.

For now you should try waiting 10-20 minutes or even more. It's still processing video data but very slowly. Don't preview or modify any of those 2 files. I'll see if I can get this fixed somehow.

**Comment by fefo-dev** [comment] 2021-08-28 15:46
Makes sense, after all you have to re-encode everything.

Thankfully it doesn't damage the main file. I'll use it sparingly since it's short-lived anyway.

**Comment by Davidj361** [comment] 2021-08-28 20:21
> Makes sense, after all you have to re-encode everything.
It is not re-encoding because that would cause loss in quality as you would be essentially applying a lossy compression on data that already had a lossy compression applied on it. The plugins should be essentially doing the same thing as `ffmpeg -i yourvid.mkv -c copy out.mkv` where it does not re-encode by instead copies all video & audio data. This is called remuxing instead of re-encoding. The code I've used is from here: [](https://ffmpeg.org/doxygen/trunk/remuxing_8c-example.html).

I'll have to look at why it takes so long to do this with large & lengthy video files. There should be 0 CPU usage in encoding video and audio data but instead be purely video & audio stream duplication. So it's either oversight of the algorithm or the thread in charge of this is being put to sleep too much.

**Comment by mauvealerts** [comment] 2021-08-30 11:34
I'm seeing the slow write with 3.5% CPU usage by OBS, albeit at a very low CPU clock speed (i.e. due to power management). It's pushing ~350MB/s on a SATA SSD, which sounds low but I'm seeing similar performance from LosslessCut, which also uses ffmpeg. OBS remux to MP4 is doing a little better ~450 MB/s

Interestingly, copy-pasting the file in Explorer is getting ~650MB/s throughput. All were measured with the same source and destination disk. Numbers are super rough, just based on looking at Task Manager.

FWIW, I think it'd be enough if there was some indication that the copy is in progress and, ideally, a percentage of bytes copied.

**Comment by Davidj361** [comment] 2021-09-01 19:56
> FWIW, I think it'd be enough if there was some indication that the copy is in progress and, ideally, a percentage of bytes copied.

I'll try adding that if I'm unable to fix this issue.

**Closed** 2021-09-07 23:00 UTC
